# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.7.0-browsers`
      - image: circleci/python:3.7.0
      - image: google/cloud-sdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: |
          sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          sudo gcloud auth configure-docker
      - run: |
          mkdir instance
          sudo gsutil cp gs://mypenny-config/flask.cfg instance/flask.cfg

      # build and push Docker image
      - run: |
          TAG=$(git log -1 --pretty=%h)
          docker build -t gcr.io/${GOOGLE_PROJECT_ID}/penny-api:$TAG .
          docker push gcr.io/${GOOGLE_PROJECT_ID}/penny-api:$TAG
